INSERT INTO T_USER_PATIENTS (
    USER_PATIENT_ID, USER_ID, PATIENT_ID, RELATIONSHIP
) VALUES (
    8001, 1001, 3001, 'Self'
);

INSERT INTO T_USER_PATIENTS (
    USER_PATIENT_ID, USER_ID, PATIENT_ID, RELATIONSHIP
) VALUES (
    8002, 1001, 3002, 'Guardian'
);
commit;